services:
  - type: web
    name: asmitraj-portfolio
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: REDIS_URL
        value: redis://red-dagrc72d0e5s73atdke0:6379

